### PR TITLE
Fix compilation with beta

### PR DESCRIPTION
**Pull request by rkjnsn**
These changes allow the code to compile with beta

### CODE REVIEW

**Comment by KokaKiwi** [comment]
Ew I really feel ashamed for not having updated the code, so thanks for your work :o
Also, it seems the tests doesn't compile, is there a way you fix it? ^^ Or maybe there's a way I can add commits too (I never did advanced things on GitHub Pull Requests :p)

**Comment by rkjnsn** [comment]
Hah! I completely forgot to run tests. Let me try to fix them really quickly and update.

**Comment by KokaKiwi** [comment]
no problem ^-^

**Comment by rkjnsn** [comment]
Okay. I updated the tests for the latest nightly. They don't build on beta, though, due to test::Bencher being unstable.

**Comment by KokaKiwi** [comment]
Ah too bad :(
i'll merge it, but I'll search if there's a way to be able to test it on beta too (eg. disabling the bench where on beta)

**Pull request merged**
